name: Continuous Deployment (Docker)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t todo-app .

      - name: Jalankan Docker Container
        run: docker run -d -p 4173:4173 todo-app
