name: Continuous Testing

on:
  push:
    branches: [main, deploy-testing]
  pull_request:
    branches: [main, deploy-testing]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependensi
        run: npm install

      - name: Jalankan unit test
        run: npm test
